<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    /* 
      Promise.any([promise1, promise2,...])
        - 所有的promise对象的状态都为pending时，则返回的promise对象的状态为pending，其PromiseResult为undefined
        - 所有的promise对象中有状态为fulfilled时，则返回的promise对象的状态为fulfilled，其PromiseResult为第一个改变状态为fulfilled的promise对象的返回值
        - 所有的promise对象的状态都为rejected时，则返回的promise对象的状态为rejected，其PromiseResult为AggregateError: All promises were rejected
          其中errors中包含所有promise对象的错误信息
    */
    const p1 = new Promise((resolve, reject) => {
      setTimeout(() => {
        try{
          console.log('p1');
          throw new Error('p1我错了...');
          resolve({name1: 'p1'});
        }
        catch(err) {
          reject(err);
        }
      }, 1500)
    })
    const p2 = new Promise((resolve, reject) => {
      setTimeout(() => {
        try{
          console.log('p2');
          throw new Error('p2我错了...');
          resolve({name2: 'p2'});
        }
        catch(err) {
          reject(err);
        }
      }, 1000)
    })
    const p3 = new Promise((resolve, reject) => {
      setTimeout(() => {
        try{
          console.log('p3');
          throw new Error('p3我错了...');
          resolve({name3: 'p3'});
        }
        catch(err) {
          reject(err);
        }
      }, 2000)
    })
    const re = Promise.any([p1, p2, p3]);
    console.log(re);
    re.then((data) => {
      console.log(data);
    }).catch((err) => {
      console.log(err.message);
    })
  </script>
</body>

</html>